apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dvapfht10-go 
  janus-idp.io/tekton: dvapfht10-go
  backstage.io/kubernetes-id: dvapfht10-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dvapfht10-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  